sudo: required
services:
  - docker

before_install:
  - docker build -t johntam/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true johntam/react-test npm test

after_success:
  - docker build -t johntam/multi-client ./client
  - docker build -t johntam/multi-nginx ./nginx
  - docker build -t johntam/multi-server ./server
  - docker build -t johntam/multi-worker ./worker

  # Take these images and push them to the hub, log into Docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push johntam/multi-client
  - docker push johntam/multi-nginx
  - docker push johntam/multi-server
  - docker push johntam/multi-worker
